// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa0qdUCrREvgFNJEqSVkpS9LabpDj3HqM',
    appId: '1:1073001033129:web:e30ae94a3773317c3c28b8',
    messagingSenderId: '1073001033129',
    projectId: 'authentication-emcus',
    authDomain: 'authentication-emcus.firebaseapp.com',
    storageBucket: 'authentication-emcus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqKPg6kIJV6ZWKEs4bOOELhfXy3reJ58',
    appId: '1:1073001033129:android:61f4233b041ff1be3c28b8',
    messagingSenderId: '1073001033129',
    projectId: 'authentication-emcus',
    storageBucket: 'authentication-emcus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxe55YCdlCNfj4tT3TIoDPIpB_T3z3Aao',
    appId: '1:1073001033129:ios:59f46ebca35170363c28b8',
    messagingSenderId: '1073001033129',
    projectId: 'authentication-emcus',
    storageBucket: 'authentication-emcus.appspot.com',
    iosBundleId: 'com.example.firebaseEmcus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxe55YCdlCNfj4tT3TIoDPIpB_T3z3Aao',
    appId: '1:1073001033129:ios:eeef40d8356128193c28b8',
    messagingSenderId: '1073001033129',
    projectId: 'authentication-emcus',
    storageBucket: 'authentication-emcus.appspot.com',
    iosBundleId: 'com.example.firebaseEmcus.RunnerTests',
  );
}
